/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nikhilspring.insurance.events;
@org.apache.avro.specific.AvroGenerated
public enum PaymentType implements org.apache.avro.generic.GenericEnumSymbol<PaymentType> {
  PREMIUM, CLAIM_PAYMENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentType\",\"namespace\":\"com.nikhilspring.insurance.events\",\"symbols\":[\"PREMIUM\",\"CLAIM_PAYMENT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
