apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service-app
spec:
  selector:
    matchLabels:
      app: policy-service-app
  template:
    metadata:
      labels:
        app: policy-service-app
    spec:
      containers:
        - name: policy-service-app
          image: insurance/policy-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: policy-service-svc
spec:
  selector:
    app: policy-service-app
  ports:
    - port: 80
      targetPort: 8082