# Default application configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/policydb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: insurance-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

logging:
  level:
    com.nikhilspring: INFO
    org.springframework.cloud: INFO
    org.springframework.security: INFO 