server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/insurancepaymentdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:9296}
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 900000 # 15 minutes in milliseconds
  # Simple Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ljd1xbrz4gjmjlac.us.auth0.com/

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}