server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:9296}
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id : POLICY-SERVICE
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/**
          filters:
            - name: CircuitBreaker
              args:
                name: POLICY-SERVICE
                fallbackuri: forward:/policyServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: CLAIM-SERVICE
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claim/**
          filters:
            - name: CircuitBreaker
              args:
                name: CLAIM-SERVICE
                fallbackuri: forward:/claimServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 14RR6sCVdCqgXu1N67jTQYaxAOvPZYov
            client-secret: Y-4xr5FhSF3D2RsgMFRkhdTaIJF3TwKWu4Yo7r8Orv5gg9GTJ-2XrI5WabSmQ_Zh
            scope: openid, email, profile, offline_access, Customer, Admin
            authorization-grant-type: authorization_code  # ✅ Ensure it's `authorization_code`
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            #client-authentication-method: client_secret_basic
        provider:
          auth0:
            issuer-uri: https://dev-ljd1xbrz4gjmjlac.us.auth0.com/
            jwk-set-uri: https://dev-ljd1xbrz4gjmjlac.us.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: https://dev-ljd1xbrz4gjmjlac.us.auth0.com/

auth0:
  audience: https://dev-ljd1xbrz4gjmjlac.us.auth0.com/api/v2/